services:
  - type: web
    name: myportfolio-web
    runtime: python
    plan: free
    region: oregon
    buildCommand: pip install -r requirements.txt
    preDeployCommand: python myportfolio/manage.py migrate --noinput && python myportfolio/manage.py collectstatic --noinput
    startCommand: gunicorn myportfolio.wsgi:application --chdir myportfolio
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: false
      - key: DJANGO_ALLOWED_HOSTS
        value: .onrender.com,localhost,127.0.0.1
      - key: DJANGO_CSRF_TRUSTED_ORIGINS
        value: https://*.onrender.com
      - key: SERVE_MEDIA_LOCALLY
        value: true
      - key: DATABASE_URL
        fromDatabase:
          name: myportfolio-db
          property: connectionString

databases:
  - name: myportfolio-db
    plan: free
    region: oregon
    databaseName: myportfolio
