# Generated by Django 5.1.5 on 2025-09-02 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_icon', models.CharField(max_length=155)),
                ('feature_user', models.CharField(max_length=55)),
                ('feature_title', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='AboutSml',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_title', models.CharField(max_length=200)),
                ('about_des', models.TextField()),
            ],
        ),
    ]
