# Generated by Django 5.1.5 on 2025-09-02 14:49

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('About_Page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutsml',
            name='about_des',
            field=tinymce.models.HTMLField(),
        ),
    ]
