# Generated by Django 5.1.5 on 2026-04-05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('About_Page', '0002_alter_aboutsml_about_des'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('student_role', models.CharField(max_length=100)),
                ('review_text', models.TextField()),
                ('rating', models.PositiveSmallIntegerField(default=5)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='testimonial/')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['display_order', '-created_at'],
            },
        ),
    ]
