# Generated by Django 6.0 on 2026-03-05 16:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.PositiveBigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DashboardCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_icon', models.CharField(max_length=200)),
                ('course_title', models.CharField(max_length=200)),
                ('course_fees', models.CharField(max_length=55)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, default='default/user.png', null=True, upload_to='User_Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('date_of_birth', models.DateField()),
                ('cnic', models.CharField(max_length=15)),
                ('country', models.CharField(choices=[('Pakistan', 'Pakistan')], default='Pakistan', max_length=55)),
                ('province', models.CharField(choices=[('Punjab', 'Punjab'), ('Sindh', 'Sindh'), ('khyber_pakhtunkhwa', 'Khyber Pakhtunkhwa'), ('Balochistan', 'Balochistan')], max_length=55)),
                ('district', models.CharField(max_length=55)),
                ('address', models.TextField()),
                ('phone_code', models.CharField(choices=[('+92', '+92 (Pakistan)')], max_length=55)),
                ('phone', models.CharField(max_length=10)),
                ('education', models.CharField(choices=[('Matric', 'Matric'), ('Inter', 'Intermediate'), ('Bs', 'Bachelor (BS)'), ('Master', 'Master (MS / MA / MSc)'), ('Mphill', 'MPhill'), ('phd', 'PhD')], max_length=55)),
            ],
        ),
        migrations.CreateModel(
            name='CourseLecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('video_url', models.URLField()),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lectures', to='Dashboard_Page.courseweek')),
            ],
        ),
        migrations.AddField(
            model_name='courseweek',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weeks', to='Dashboard_Page.dashboardcourse'),
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_paid', models.BooleanField(default=False)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dashboard_Page.dashboardcourse')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'course')},
            },
        ),
    ]
