# Generated by Django 6.0 on 2026-03-06 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard_Page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Updates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updation_date', models.DateField()),
                ('updation_title', models.CharField(max_length=255)),
                ('updation_desc', models.TextField()),
                ('updation_tag', models.CharField(choices=[('news', 'News'), ('event', 'Event'), ('announcement', 'Announcement'), ('course', 'Course')], max_length=55)),
                ('button_type', models.CharField(choices=[('read', 'Read More'), ('register', 'Register Now'), ('schedule', 'View Schedule'), ('course', 'Go to Course')], max_length=55)),
                ('button_link', models.CharField(max_length=255)),
            ],
        ),
    ]
