# Generated by Django 6.0 on 2026-03-07 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard_Page', '0002_updates'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportantLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_title', models.CharField(max_length=255)),
                ('link_desc', models.TextField()),
                ('link_icon', models.CharField(choices=[('fa-solid fa-file-pdf', 'PDF'), ('fa-solid fa-file-word', 'Word'), ('fa-solid fa-video', 'Video'), ('fa-solid fa-link', 'Link')], default='fa-solid fa-link', max_length=55)),
                ('important_link', models.URLField()),
                ('is_new', models.BooleanField(default=True)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
