# Generated by Django 5.1.5 on 2025-05-02 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mycourses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mycourses',
            name='course_image',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='courses/'),
        ),
    ]
