# Generated by Django 5.1.5 on 2025-05-02 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mycourses', '0002_mycourses_course_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='mycourses',
            name='course_duration',
            field=models.CharField(default='dur', max_length=55),
        ),
        migrations.AddField(
            model_name='mycourses',
            name='course_level',
            field=models.CharField(default='level', max_length=55),
        ),
    ]
