# Generated by Django 5.1.5 on 2025-09-24 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contact_Page', '0002_rename_is_replied_contactmessage_is_read_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapSide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Address', models.CharField(max_length=200)),
                ('PhoneNumber', models.CharField(max_length=14)),
                ('Email', models.CharField(max_length=200)),
                ('MapLink', models.TextField()),
            ],
        ),
    ]
