# Generated by Django 5.1.5 on 2025-10-17 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Contact_Page', '0003_mapside'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmessage',
            name='is_read',
        ),
    ]
