# Generated by Django 5.1.5 on 2025-09-01 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_icon', models.CharField(max_length=300)),
                ('feature_title', models.CharField(max_length=150)),
                ('feature_des', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='FounderMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_founder', models.CharField(max_length=200)),
                ('message_title', models.CharField(max_length=300)),
                ('founder_message', models.TextField()),
                ('founder_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instruct_img', models.FileField(default=None, max_length=250, null=True, upload_to='instructors/')),
                ('instruct_name', models.CharField(max_length=55)),
                ('instruct_skill', models.CharField(max_length=55)),
                ('about_instruct', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nav_logo', models.FileField(default=None, max_length=250, null=True, upload_to='background/')),
                ('nav_title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Top_Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_image', models.FileField(default=None, max_length=250, null=True, upload_to='courses/')),
                ('course_title', models.CharField(max_length=150)),
                ('course_des', models.TextField()),
                ('course_duration', models.CharField(max_length=55)),
                ('course_price', models.CharField(max_length=100)),
            ],
        ),
    ]
