# Generated by Django 5.1.5 on 2026-04-05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_Page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_class', models.CharField(default='fas fa-angle-right', max_length=80)),
                ('value', models.CharField(max_length=255)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FooterLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('quick', 'Quick Links'), ('course', 'Courses')], max_length=10)),
                ('label', models.CharField(max_length=100)),
                ('url', models.CharField(default='#', max_length=255)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FooterSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Smart LMS', max_length=100)),
                ('about_text', models.TextField()),
                ('newsletter_text', models.CharField(default='Subscribe to get update about new courses.', max_length=255)),
                ('newsletter_placeholder', models.CharField(default='Enter your email', max_length=100)),
                ('newsletter_button_text', models.CharField(default='Subscribe', max_length=30)),
                ('copyright_text', models.CharField(max_length=255)),
                ('project_note', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='FooterSocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=40)),
                ('icon_class', models.CharField(max_length=80)),
                ('url', models.CharField(default='#', max_length=255)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
    ]
