# Generated by Django 6.0 on 2026-04-29 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_Page', '0002_footer_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='logo',
            name='favicon',
            field=models.ImageField(default=None, null=True, upload_to='favicon/'),
        ),
    ]
